// Inventário de Dons Espirituais — Lourenço Stelio Rega
// Escala: Muito=4, Às vezes=2, Raramente=1, Nunca=0
// Dom com pontuação >= 17 é considerado um dom presente.

const QUESTIONS = [
  "Gosto de organizar ideias, pessoas, coisas e o tempo, tendo em vista um serviço mais efetivo e produtivo para o Senhor.",
  "Tenho alegria em trabalhar com as pessoas ignoradas ou desconhecidas da maioria.",
  "Adapto-me facilmente a uma situação ou ambiente diferente.",
  "Tenho facilidade em selecionar e relacionar entre si fatos importantes das Escrituras.",
  "Tenho prazer em ajudar os líderes de maior responsabilidade, aliviando-os de tarefas menores de seu trabalho.",
  "Eu percebo sem dificuldade a diferença entre o que é certo e o que é errado.",
  "Gosto de levar outras pessoas a uma decisão relacionada com a salvação.",
  "Tenho facilidade em encorajar e animar as pessoas indecisas e cheias de problemas.",
  "Quando percebo a vontade de Deus, posso ir em frente, apesar da oposição ou falta de apoio.",
  "Me sinto realizado com a oportunidade de ajudar as pessoas a conhecer os detalhes sobre um assunto complicado.",
  "Gostaria de me envolver em atividades que promovam o crescimento de um grupo de crentes levando-os ao amadurecimento na vida cristã.",
  "Sinto alegria em comunicar a vontade de Deus e faço de maneira contagiante, persuasiva e clara, tendo certeza de que falo da parte de Deus.",
  "Sonho em ter mais dinheiro para poder repartir com as pessoas necessitadas.",
  "As minhas sugestões às pessoas para ajudá-las em suas decisões geralmente dão certo.",
  "Tenho facilidade em fazer planos de ação para que, com outras pessoas, possamos atingir um objetivo.",
  "Gosto de visitar hospitais ou lares de pessoas necessitadas e me sinto abençoado com isso.",
  "Eu fico empolgado com o sucesso do trabalho missionário em outros Estados e no estrangeiro.",
  "Gosto de analisar bem todos os fatos até entendê-los.",
  "Fico à vontade quando posso ser útil em fazer certas coisas auxiliares para ajudar quem é líder, como arrumar cadeiras, transportar objetos, manter a ordem das coisas etc.",
  "Posso constatar a falsidade antes que ela se torne evidente às outras pessoas.",
  "Tenho facilidade em iniciar uma conversa com uma pessoa estranha e levá-la ao conhecimento do evangelho.",
  "Tenho facilidade em entender os problemas dos outros e apontar-lhes os rumos de possíveis soluções.",
  "Tenho convicção da presença e atuação divina em minha vida diariamente.",
  "Procuro explicar as questões complicadas da Bíblia de modo que outros me entendam sem dificuldade.",
  "Tenho prazer em ser útil na recuperação espiritual de crentes que se afastaram do Senhor e da igreja.",
  "Tenho alegria se sou solicitado a pregar (nos lares, no templo, ao ar livre etc).",
  "Quando ajudo uma pessoa necessitada, deixo de lado qualquer pensamento sobre vantagens materiais ou espirituais.",
  "De várias alternativas, escolho a opção que normalmente funciona.",
  "Quando alguma organização a que pertenço tem algum problema a enfrentar, intimamente procuro pensar nas possíveis soluções.",
  "Sinto-me realizado quando posso fazer algo por uma pessoa doente ou em necessidade.",
  "Tenho prazer em cooperar nos trabalhos pioneiros de minha igreja, como iniciar um novo ponto de pregação ou congregação etc.",
  "Gosto de analisar e entender bem todas as coisas, antes de aceitá-las.",
  "Em ocasiões de emergência tenho prazer em ajudar os líderes de maior responsabilidade para que as coisas se normalizem.",
  "Quando alguém está conversando comigo, geralmente percebo se não está dizendo a verdade.",
  "Gosto de cooperar com os trabalhos de evangelização de minha igreja, como séries de conferências, pregações ao ar livre, nas congregações etc.",
  "Aceito sem dificuldades as impertinências e os erros das pessoas, crendo que uma conversa pessoal com elas é o melhor remédio.",
  "Mesmo em tempos difíceis, tenho convicção na provisão e ajuda contínua de Deus.",
  "Quando vou explicar uma coisa a uma pessoa, gosto de me colocar no lugar dela para sentir suas dificuldades em aprender.",
  "Tenho compaixão pelos crentes que vacilam na fé, e se pudesse, procuraria tomar providências para a sua recuperação.",
  "Acredito que a melhor maneira de levar o povo de Deus a uma vida mais dedicada é através da admoestação pela pregação pública da Palavra de Deus.",
  "Quando há alguma necessidade financeira ou material na igreja ou na vida de alguém, logo penso em contribuir com minhas posses para ajudar.",
  "Sempre que uma pessoa está com problemas, a solução me vem de Deus através de um versículo da Bíblia.",
  "Tenho facilidade em descobrir as falhas de uma organização e de elaborar um plano de ação para a devida correção.",
  "Sinto compaixão quando vejo alguma pessoa doente ou com problemas.",
  "Se Deus me chamasse, gostaria de pregar o evangelho num local distante.",
  "Me sinto incomodado enquanto não entendo completamente um texto bíblico, indo atrás de informações para seu esclarecimento.",
  "Tenho prazer em servir de introdutor, em auxiliar a manter a ordem ou realizar qualquer trabalho auxiliar para que a obra de Deus se realize.",
  "Sinto quando as coisas não vão dar certo.",
  "A ênfase de minha mensagem ou conversas tem sido a salvação em Cristo.",
  "Quando alguma pessoa está em pecado, a ênfase de minha preocupação é ajudá-la, ainda que perceba que outros a critiquem.",
  "Vários problemas sem solução já foram resolvidos porque eu cri que Deus os resolveria.",
  "Sinto necessidade de entender bem as coisas para poder explicá-las aos outros.",
  "Tenho prazer em alimentar os crentes com a Palavra de Deus.",
  "Quando há algum problema na igreja, acredito que somente pela pregação sobre o assunto, ele pode ser resolvido.",
  "Tenho a tendência de contribuir para a obra de Deus com um percentual maior do que o exigido.",
  "Quando leio um texto bíblico geralmente penso em suas lições práticas.",
  "Consigo imaginar um evento que precisa ser realizado, prevendo os problemas a serem enfrentados e buscando formas de resolvê-los.",
  "Identifico-me com as pessoas que estão sofrendo, e desejo ajudá-las no processo de restauração.",
  "Gosto de iniciar trabalhos novos na área de evangelização.",
  "Me interesso em saber como as coisas funcionam.",
  "Tenho prazer em providenciar certos detalhes para que o trabalho da igreja alcance seus objetivos, como anotar os nomes de visitantes, controlar o aparelho de som/vídeo num culto, arrumar cadeiras, secretariar uma reunião etc.",
  "Tenho facilidade em perceber se uma atitude é certa ou errada e geralmente isso se confirma.",
  "Busco oportunidades no relacionamento com descrentes para evangelizá-los.",
  "Para mim o potencial das pessoas tem mais valor do que seus atos.",
  "Já fui surpreendido com respostas imediatas às minhas orações.",
  "Quando assisto uma aula dada por alguém que não sabe ensinar direito, fico pensando numa maneira diferente em que ela teria melhor rendimento no ensino.",
  "Sinto prazer em orientar os crentes como um pastor às suas ovelhas.",
  "Sinto-me responsável por confrontar as pessoas com a verdade.",
  "Administro as minhas finanças e bens para que possa contribuir mais para a obra de Deus.",
  "Penso em soluções de problemas que normalmente as pessoas não pensariam.",
  "Tenho interesse em entender como as organizações funcionam.",
  "Tenho compaixão pelas pessoas consideradas inúteis, sem esperança ou que estão sofrendo.",
  "Havendo oportunidade, estou disposto a me oferecer para participar ativamente no começo de uma nova igreja.",
  "Gosto de entender bem as questões complicadas da Bíblia.",
  "Ainda que a pregação da Palavra seja importante, creio que meu papel é ajudar nos detalhes de bastidores ou na retaguarda.",
  "Posso discernir com certa precisão o caráter de uma pessoa baseado apenas nas primeiras impressões que tenho dela.",
  "Preocupo-me com a salvação de meus parentes, amigos, vizinhos e colegas.",
  "Gosto de encorajar e fortalecer as pessoas que estão abatidas e tristes.",
  "Em situações onde o sucesso não pode ser garantido somente pelo esforço humano, eu confio na providência divina em vez de me desesperar.",
  "Se tiver oportunidade, gostaria de ensinar a Bíblia de modo que os ouvintes tenham o desejo de estudá-la mais.",
  "Se pudesse, gostaria de investir tempo nutrindo e cuidando dos crentes que estão em processo de crescimento espiritual.",
  "Quando percebo uma situação de pecado, sinto-me compelido a denunciá-lo e desafiar as pessoas envolvidas ao arrependimento.",
  "Acredito que o Senhor tem me dado recursos em abundância para que eu possa contribuir mais para a sua obra.",
  "Tenho facilidade em encontrar soluções simples e práticas no meio de discussões ou de situações de conflito ou confusão."
];

// Mapeamento dom -> índices (0-based) das perguntas
const GIFTS = [
  { key: "A", name: "Administração/Liderança", q: [1,15,29,43,57,71] },
  { key: "B", name: "Misericórdia",            q: [2,16,30,44,58,72] },
  { key: "C", name: "Missionário",             q: [3,17,31,45,59,73] },
  { key: "D", name: "Conhecimento",            q: [4,18,32,46,60,74] },
  { key: "E", name: "Serviço/Diaconia",        q: [5,19,33,47,61,75] },
  { key: "F", name: "Discernimento de Espírito", q: [6,20,34,48,62,76] },
  { key: "G", name: "Evangelista",             q: [7,21,35,49,63,77] },
  { key: "H", name: "Aconselhamento",          q: [8,22,36,50,64,78] },
  { key: "I", name: "Fé",                      q: [9,23,37,51,65,79] },
  { key: "J", name: "Ensino",                  q: [10,24,38,52,66,80] },
  { key: "L", name: "Pastor-Mestre",           q: [11,25,39,53,67,81] },
  { key: "M", name: "Profeta",                 q: [12,26,40,54,68,82] },
  { key: "N", name: "Repartir",                q: [13,27,41,55,69,83] },
  { key: "O", name: "Sabedoria",               q: [14,28,42,56,70,84] }
];

const GIFT_DESC = {
  "A": "Coordenar atividades, planejar etapas de um plano de ação, detectar problemas numa organização e liderar áreas da igreja.",
  "B": "Interessar-se pelo sofrimento e carências dos outros, visitar enfermos, ajudar os que estão em desgraça — o assistente social da igreja.",
  "C": "Fundar novos trabalhos, iniciar frentes missionárias, ir a outra cidade, Estado ou país para alcançar quem ainda não é salvo.",
  "D": "Buscar conhecimento e esclarecimentos da Palavra, reconhecer fatos e verdades-chave das Escrituras, sistematizar os grandes fatos da Bíblia.",
  "E": "Descobrir e suprir as necessidades da igreja, estar à disposição para tarefas de bastidores — o verdadeiro diaconato.",
  "F": "Detectar a falsidade e a verdade, sentir a diferença entre sintomas e causas de uma ação, alertar a igreja diante de riscos.",
  "G": "Evangelizar, expor o Evangelho levando os não crentes à salvação.",
  "H": "Preocupar-se com o crescimento espiritual, aconselhar, confortar e encorajar, despertar novo interesse espiritual nas pessoas.",
  "I": "Ver algo que precisa ser feito e crer que Deus fará, mesmo parecendo impossível — a fé que move montanhas.",
  "J": "Esclarecer a verdade, transmitir detalhes específicos de um assunto, fazer com que outros aprendam a Palavra.",
  "L": "Orientar o povo de Deus no dia-a-dia, aconselhar quem está confuso, alimentar através do ensino e socorrer nas necessidades espirituais.",
  "M": "Pregação, admoestação quanto ao caminho de Deus, auxiliar o povo a descobrir o caminho de Deus em decisões importantes.",
  "N": "Conseguir recursos para dar e repartir, capacitar outros com sua contribuição, sentir realização ao ver um objetivo alcançado.",
  "O": "Perceber as verdadeiras causas de uma situação, ter sempre uma palavra sábia e prática, aplicar o conhecimento a situações específicas."
};

const THRESHOLD = 17;
